# Generated by Django 3.1.7 on 2021-03-24 10:52

from django.db import migrations
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mdeditor_demo_app', '0002_examplemodel_content_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='content2',
            field=mdeditor.fields.MDTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
